# Generated by Django 3.2.3 on 2021-06-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_pizzamodel_hotelmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('bookedhotel', models.CharField(max_length=20)),
            ],
        ),
    ]
