# Generated by Django 3.2.3 on 2021-06-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210613_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_Main_Img',
            field=models.ImageField(default='image', upload_to='images/'),
            preserve_default=False,
        ),
    ]
