# Generated by Django 3.2.3 on 2021-06-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaModel',
            new_name='HotelModel',
        ),
    ]
