# Generated by Django 3.1.8 on 2021-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210615_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='totalprice',
            field=models.CharField(default='dd', max_length=10),
            preserve_default=False,
        ),
    ]
