# Generated by Django 3.2.3 on 2021-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210616_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_Main_Img1',
            field=models.ImageField(default='e', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_Main_Img2',
            field=models.ImageField(default='e', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_Main_Img3',
            field=models.ImageField(default='e', upload_to='images/'),
            preserve_default=False,
        ),
    ]
