# Generated by Django 3.1.8 on 2021-06-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20210618_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checkin',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='checkout',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
