# Generated by Django 3.1.8 on 2021-06-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20210619_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='book',
            name='checkout',
        ),
    ]
