# Generated by Django 3.1.8 on 2021-06-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20210619_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checkin',
            field=models.CharField(default='2', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='checkout',
            field=models.CharField(default='2', max_length=10),
            preserve_default=False,
        ),
    ]
