# Generated by Django 3.2.3 on 2021-06-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20210619_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='book',
            name='checkout',
        ),
    ]
