# Generated by Django 3.1.8 on 2021-06-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('bookedhotel', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('Hotel_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=5)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
                ('hotel_Main_Img1', models.ImageField(upload_to='images/')),
                ('hotel_Main_Img2', models.ImageField(upload_to='images/')),
                ('hotel_Main_Img3', models.ImageField(upload_to='images/')),
                ('totalprice', models.CharField(max_length=10)),
            ],
        ),
    ]
