# Generated by Django 3.1.8 on 2021-06-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookedhotel',
        ),
    ]
